"""Plot real regression metrics for the best model (prefer XGBoost).

Run:
    python d.py

Output:
    ml_best_model_metrics.png
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams["figure.dpi"] = 300

# Path to model_results.csv generated by train_battery_model.py
ROOT = "/Users/chaitanyaattanti/version-2/MAHA-EV-DASHBOARD/ML"
RESULTS_CSV = os.path.join(ROOT, "ml_output", "model_results.csv")

results = pd.read_csv(RESULTS_CSV)

# Prefer XGBoost row; if missing, use best R2
if "XGBoost" in results["Model"].values:
    row = results.loc[results["Model"] == "XGBoost"].iloc[0]
    model_name = "XGBoost (best model)"
else:
    row = results.sort_values("R2", ascending=False).iloc[0]
    model_name = f"{row['Model']} (best model)"

mae  = float(row["MAE"])
rmse = float(row["RMSE"])
r2   = float(row["R2"])

metrics_names  = ["MAE", "RMSE", "R²"]
metrics_values = np.array([mae, rmse, r2])

x = np.arange(len(metrics_names))

fig, ax = plt.subplots(figsize=(5, 3))
bars = ax.bar(
    x,
    metrics_values,
    0.6,
    color=["#ffd6e8", "#ffe4b5", "#d0e4ff"],
    edgecolor="black",
)

ax.set_ylabel("Value", fontsize=9)
ax.set_xticks(x)
ax.set_xticklabels(metrics_names, fontsize=8)
ax.set_ylim(0, max(metrics_values) * 1.2)
ax.set_title(model_name, fontsize=9)

for rect, val in zip(bars, metrics_values):
    ax.text(
        rect.get_x() + rect.get_width() / 2,
        val + 0.02 * max(metrics_values),
        f"{val:.3f}",
        ha="center",
        va="bottom",
        fontsize=7,
    )

fig.tight_layout()
plt.savefig("ml_best_model_metrics.png", bbox_inches="tight", transparent=False)
plt.close()